张量Tensor

In [1]:
import torch 

In [4]:
x=torch.arange(12).reshape(3,4)
y=torch.tensor([[3,4,5,6],[6,7,8,9],[9,10,11,12]],dtype=torch.float32)
x,y

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 3.,  4.,  5.,  6.],
         [ 6.,  7.,  8.,  9.],
         [ 9., 10., 11., 12.]]))

In [10]:
c1=torch.cat((x,y),dim=0)
c2=torch.cat((x,y),dim=1)
c1,c2

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 3.,  4.,  5.,  6.],
         [ 6.,  7.,  8.,  9.],
         [ 9., 10., 11., 12.]]),
 tensor([[ 0.,  1.,  2.,  3.,  3.,  4.,  5.,  6.],
         [ 4.,  5.,  6.,  7.,  6.,  7.,  8.,  9.],
         [ 8.,  9., 10., 11.,  9., 10., 11., 12.]]))

In [12]:
sum1=x.sum()
sum2=x.sum(dim=0)
sum3=x.sum(dim=1)
sum1,sum2,sum3


(tensor(66), tensor([12, 15, 18, 21]), tensor([ 6, 22, 38]))

In [13]:
a = torch.tensor(5.5)
a,a.item(),float(a),int(a)

(tensor(5.5000), 5.5, 5.5, 5)