数据操作

In [1]:
import torch

In [3]:
x=torch.arange(12)
x
x.numel()

12

In [8]:
x=x.reshape(3,4)

In [9]:
torch.zeros((2,3,4))
torch.ones((2,3,4))
torch.tensor([[1,2,3,4],[1,2,3,4],[1,2,3,4]])

tensor([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]])

广播机制

In [12]:
a=torch.arange(3).reshape(3,1)
b=torch.arange(2).reshape(1,2)
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [13]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

转换为numpy张量

In [14]:
A=x.numpy()
B=torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

创造人工数据集

In [24]:
import os
os.makedirs(os.path.join('..','data'),exist_ok=True)
data_file=os.path.join('..','data','house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 写入列名（特征：房间数、巷子类型、价格）
    f.write('1,Pave,127500\n')          # 第1个样本
    f.write('2,NA,106000\n')          # 第2个样本
    f.write('4,NA,178100\n')          # 第3个样本
    f.write('NA,NA,140000\n')         # 第4个样本（房间数为缺失值）

In [25]:
import pandas as pd
data=pd.read_csv(data_file)
display(data)

NumRooms Alley   Price
0       1.0  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [35]:
inputs,outputs = data.iloc[:,0:2],data.iloc[:,2]
inputs['NumRooms']=inputs['NumRooms'].fillna(inputs['NumRooms'].mean())
inputs

NumRooms Alley
0  1.000000  Pave
1  2.000000   NaN
2  4.000000   NaN
3  2.333333   NaN

In [36]:
inputs= pd.get_dummies(inputs,dummy_na=True)
inputs

NumRooms  Alley_Pave  Alley_nan
0  1.000000        True      False
1  2.000000       False       True
2  4.000000       False       True
3  2.333333       False       True