In [6]:
import torch

In [7]:

# 练习 1: 创建服从特定正态分布的张量
def exercise1():
    # 使用 torch.randn 生成标准正态分布，然后乘以标准差 0.1
    tensor = torch.randn(7, 9) * 0.1
    print("练习1结果:")
    print(f"形状: {tensor.shape}")
    print(f"均值: {tensor.mean().item():.4f}, 标准差: {tensor.std().item():.4f}")
    print()

# 练习 2: 张量重塑和维度交换
def exercise2():
    v = torch.arange(24)  # 创建0-23的向量
    print("原始向量:", v)
    
    # 原地重塑为 (2, 3, 4) 并交换维度0和2
    v = v.view(2, 3, 4).transpose(0, 2)
    
    print("练习2结果:")
    print(f"最终形状: {v.shape}")
    print(f"内容:\n{v}")
    print()

# 练习 3: 行中心化
def exercise3():
    # 创建一个示例二维张量
    A = torch.tensor([[1.0, 2, 3], 
                     [4, 5, 6], 
                     [7, 8, 9]])
    
    # 计算行均值并保持维度以便广播
    row_means = A.mean(dim=1, keepdim=True)
    
    # 每行减去该行均值
    A_centered = A - row_means
    
    print("练习3结果:")
    print("原始张量:\n", A)
    print("行均值:\n", row_means)
    print("中心化后:\n", A_centered)
    print()

# 练习 4: 压缩尺寸为1的维度
def exercise4():
    # 创建示例张量
    B = torch.rand(6, 1, 7, 1)
    print("原始形状:", B.shape)
    
    # 压缩所有尺寸为1的维度
    B_squeezed = B.squeeze()
    
    print("练习4结果:")
    print("压缩后形状:", B_squeezed.shape)
    print()

# 练习 5: 广播乘法
def exercise5():
    # 创建示例张量
    P = torch.rand(2, 3, 4)
    Q = torch.rand(4, 5)
    
    # 方法1: 使用unsqueeze扩展维度
    result1 = P.unsqueeze(3) * Q.unsqueeze(0).unsqueeze(0)
    
    # 方法2: 更简洁的写法
    result2 = P[..., None] * Q
    
    print("练习5结果:")
    print("P形状:", P.shape)
    print("Q形状:", Q.shape)
    print("广播乘法结果形状:", result1.shape)
    print("两种方法结果是否相同:", torch.allclose(result1, result2))
    print()

# 运行所有练习
if __name__ == "__main__":
    exercise1()
    exercise2()
    exercise3()
    exercise4()
    exercise5()

练习1结果:
形状: torch.Size([7, 9])
均值: 0.0064, 标准差: 0.0970

原始向量: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])
练习2结果:
最终形状: torch.Size([4, 3, 2])
内容:
tensor([[[ 0, 12],
         [ 4, 16],
         [ 8, 20]],

        [[ 1, 13],
         [ 5, 17],
         [ 9, 21]],

        [[ 2, 14],
         [ 6, 18],
         [10, 22]],

        [[ 3, 15],
         [ 7, 19],
         [11, 23]]])

练习3结果:
原始张量:
 tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
行均值:
 tensor([[2.],
        [5.],
        [8.]])
中心化后:
 tensor([[-1.,  0.,  1.],
        [-1.,  0.,  1.],
        [-1.,  0.,  1.]])

原始形状: torch.Size([6, 1, 7, 1])
练习4结果:
压缩后形状: torch.Size([6, 7])

练习5结果:
P形状: torch.Size([2, 3, 4])
Q形状: torch.Size([4, 5])
广播乘法结果形状: torch.Size([2, 3, 4, 5])
两种方法结果是否相同: True

