创建张量

In [2]:
import torch
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
X = x.reshape(3,4)  
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
print(x.shape)  
x.numel() 

torch.Size([12])


12

In [5]:
print(torch.zeros((1,2,3)))  #特定形状元素全为零的张量
torch.ones((1,2,3))

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])


tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [6]:
torch.randn(3,4)

tensor([[ 0.4857,  0.6133, -0.3323, -0.0916],
        [-0.6502, -0.6890,  1.5022,  0.5714],
        [-1.3358, -0.8833, -1.0525,  0.5084]])

In [7]:
torch.tensor([[1,2,3],[4,5,6],[7,8,9]]) 

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

张量计算

In [8]:
x = torch.tensor([1.0,2,3,4])
y = torch.tensor([2,4,5,6])
x+y,x-y,x*y,x/y,x**y  #标准算数运算

(tensor([ 3.,  6.,  8., 10.]),
 tensor([-1., -2., -2., -2.]),
 tensor([ 2.,  8., 15., 24.]),
 tensor([0.5000, 0.5000, 0.6000, 0.6667]),
 tensor([1.0000e+00, 1.6000e+01, 2.4300e+02, 4.0960e+03]))

In [9]:
X = torch.arange(12,dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0,1,4,3],[3,4,5,6],[1,2,3,4]])
torch.cat((X,Y),dim=0)  #在行上将两个张量连接起来

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 3.,  4.,  5.,  6.],
        [ 1.,  2.,  3.,  4.]])

In [ ]:
X == Y , X > Y , X < Y

(tensor([[False,  True, False,  True],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False, False, False, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]),
 tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [11]:

X.sum() 

tensor(66.)

In [12]:
#广播机制
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [ ]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [20]:
#节省内存
Z = torch.zeros_like(Y)  
print('id(Z):', id(Z))  
Z[:] = X + Y          
print('id(Z):', id(Z))

id(Z): 1941405648448
id(Z): 1941405648448


In [21]:

before = id(X)
X += Y          #使用原地操作符（如+=）将结果分配给先前分配的数组
id(X) == before

True

In [18]:
#将张量转换为numpy中的张量
A = X.numpy()
B = torch.tensor(A)
C = B.numpy()
type(A), type(B),type(C)

(numpy.ndarray, torch.Tensor, numpy.ndarray)

In [19]:

#张量转换为Python标量
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [ ]:
import os

# 1. 定义数据存储目录和文件名（
data_dir = 'D:'  
os.makedirs(data_dir, exist_ok=True)  
data_file = os.path.join(data_dir, 'student_scores.csv')  

# 2. 写入CSV数据
with open(data_file, 'w', encoding='utf-8') as f:   
    f.write('StudentID,Name,Math,English,Class\n')
    f.write('001,张三,95,88,高一(1)班\n')
    f.write('002,李四,82,NA,高一(2)班\n')
    f.write('003,王五,NA,90,高一(1)班\n')
    f.write('004,赵六,78,85,NA\n')
    f.write('005,钱七,92,89,高一(3)班\n')
#数据加载
import pandas as pd
data = pd.read_csv(data_file)

In [ ]:
#处理数据
#   插值法（ .fillna( . ) ）
inputs, outputs = data.iloc[:, 0:2], data.iloc[:,2]
inputs = inputs.fillna( inputs.mean(numeric_only=True) )
print(inputs)

inputs = pd.get_dummies(inputs, dummy_na=True)
inputs = inputs.astype(int)
print(inputs)

   StudentID Name
0          1   张三
1          2   李四
2          3   王五
3          4   赵六
4          5   钱七
   StudentID  Name_张三  Name_李四  Name_王五  Name_赵六  Name_钱七  Name_nan
0          1        1        0        0        0        0         0
1          2        0        1        0        0        0         0
2          3        0        0        1        0        0         0
3          4        0        0        0        1        0         0
4          5        0        0        0        0        1         0


In [ ]:
#   数值型dataframe转化为张量
import torch
x,y = torch.tensor(inputs.values), torch.tensor(outputs.values)
print(x,y,sep="\n")

# 将大小为1的张量转换为Python标量
a = torch.tensor([3.5]) # 创建一个大小为1的张量
result = (a, a.item(), float(a), int(a)) # 多种方式将其转为Python标量

tensor([[1, 1, 0, 0, 0, 0, 0],
        [2, 0, 1, 0, 0, 0, 0],
        [3, 0, 0, 1, 0, 0, 0],
        [4, 0, 0, 0, 1, 0, 0],
        [5, 0, 0, 0, 0, 1, 0]])
tensor([95., 82., nan, 78., 92.], dtype=torch.float64)
