In [1]:
import torch
x=torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [ ]:
x.requires_grad_(True)#存储梯度
x.grad

In [6]:
y=2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [7]:
#调用反向传播函数
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [ ]:
#验证
x.grad==4*x 

In [8]:
#默认情况下会累计梯度，需要清除之前的值
x.grad.zero_()
y=x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [9]:
x.grad.zero_()
y=x*x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [10]:
x.grad.zero_()
y=x*x
u=y.detach()
z=u*x
z.sum().backward()
x.grad==u

tensor([True, True, True, True])

In [ ]:
#python控制流
def f(a):
    b=a*2
    while b.norn()<1000:
        b=b*2
    if b.sum()>0:
        c=b
    else:
        c=100*b
    return c